#-------------SPEED----------------------------

max_trans_vel: 0.2                  # default : 1.0
min_trans_vel: 0.01                 # default : 0.1

max_vel_x: 0.4                      # default : 0.3
min_vel_x: -0.1                     # default : -1.0

max_vel_y: 0.1                      # default : 0.06
min_vel_y: -0.1                     # default : -0.06

max_rot_vel: 0.4                    # default : 1.0
min_rot_vel: 0.01                   # default : 0.4

acc_lim_x: 0.8                      # default : 1.5
acc_lim_y: 0.8                      # default : 1.5
acc_lim_theta: 2.0                  # default : 3.2
acc_limit_trans: 0.8                # default : 1.5

#----------------------------------------------

sim_time: 1.7                       # default : 1.7
sim_granularity: 0.025              # default : 0.025

goal_distance_bias: 21.0            # default : 19.0
path_distance_bias: 30.0            # default : 33.0

occdist_scale: 0.01                 # default : 0.01

stop_time_buffer: 0.2               # default : 0.2
oscillation_reset_dist: 0.05        # default : 0.05

forward_point_distance: 0.25        # default : 0.25

scaling_speed: 0.25                 # default : 0.35
max_scaling_factor: 0.2             # default : 0.1

vx_samples: 6                       # default : 6
vy_samples: 3                       # default : 3
vtheta_samples: 15                  # default : 15

sim_period: 0.2                     # default : 0.2

xy_goal_tolerance: 0.2              # default : 0.075
yaw_goal_tolerance: 0.17            # default : 0.1
latch_xy_goal_tolerance: true       # default : true

rot_stopped_vel: 0.01               # default : 0.01
trans_stopped_vel: 0.01             # default : 0.01

penalize_negative_x: true           # default : false
