# Description: Defines a state machine for a scenario in which a robot observes a table and throws any objects on it to a trash can, thereby keeping the table clean
# Author: Alex Mitrevski
# Email: aleksandar.mitrevski@h-brs.de
sm_id: mdr_demo_throw_table_objects
states: [GO_TO_OBSERVATION_POSE, PERCEIVE_TABLE, GO_TO_TABLE, PERCEIVE_TABLE_BEFORE_PICKING, PICK_OBJECT, GO_TO_TRASH_CAN, THROW_OBJECT]
outcomes: [DONE, TIMEOUT, FAILED]
state_descriptions:
    - state:
        name: GO_TO_OBSERVATION_POSE
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: PERCEIVE_TABLE
            - transition:
                name: failed
                state: GO_TO_OBSERVATION_POSE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [OBSERVATION_POSE]
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: PERCEIVE_TABLE
        state_module_name: mdr_perception_behaviours.perceive_planes
        state_class_name: PerceivePlanes
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_TABLE
            - transition:
                name: failed
                state: PERCEIVE_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: plane_prefix
                value: table
    - state:
        name: GO_TO_TABLE
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: PERCEIVE_TABLE_BEFORE_PICKING
            - transition:
                name: failed
                state: GO_TO_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [TABLE]
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: PERCEIVE_TABLE_BEFORE_PICKING
        state_module_name: mdr_perception_behaviours.perceive_planes
        state_class_name: PerceivePlanes
        transitions:
            - transition:
                name: succeeded
                state: PICK_OBJECT
            - transition:
                name: failed
                state: PERCEIVE_TABLE_BEFORE_PICKING
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: plane_prefix
                value: table
    - state:
        name: PICK_OBJECT
        state_module_name: mdr_manipulation_behaviours.pick_closest_from_surface
        state_class_name: PickClosestFromSurface
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_TRASH_CAN
            - transition:
                name: failed
                state: PICK_OBJECT
            - transition:
                name: failed_after_retrying
                state: FAILED
            - transition:
                name: find_objects_before_picking
                state: PERCEIVE_TABLE_BEFORE_PICKING
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: picking_surface_prefix
                value: table
    - state:
        name: GO_TO_TRASH_CAN
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: THROW_OBJECT
            - transition:
                name: failed
                state: GO_TO_TRASH_CAN
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [TRASH_CAN]
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: THROW_OBJECT
        state_module_name: mdr_manipulation_behaviours.throw_object_in
        state_class_name: ThrowObjectIn
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_OBSERVATION_POSE
            - transition:
                name: failed
                state: THROW_OBJECT
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: throwing_target_name
                value: trash_can
